version: "3.7"

services:
  express:
    build:
      target: dev
    volumes:
      - ./public:/app/public:ro
      - ./.env:/app/.env:ro
      - ./index.ts:/app/index.ts:ro
      - ./src:/app/src:ro
    environment:
      - NODE_ENV=dev
